# -*- coding: utf-8 -*-
"""units.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fRZIJiVKlp7FGWRS1tM16YdXCKQD1osa
"""

#Units
inch = 1
kip = 1
sec = 1

ft = 12*inch
lb = kip/1000

ksi = kip/inch**2
ksf = kip/ft**2

psi = lb/inch**2
psf = lb/ft**2

cm = 2.54*inch
mm = 1/12*cm
m = mm*1000

rebars = {'#3':{'diam':0.375*inch,'area':0.11*inch**2},
              '#4':{'diam':0.5*inch,'area':0.2*inch**2},
              '#5':{'diam':0.625*inch,'area':0.31*inch**2},
              '#6':{'diam':0.75*inch,'area':0.44*inch**2},
              '#7':{'diam':0.875*inch,'area':0.6*inch**2},
              '#8':{'diam':1*inch,'area':0.79*inch**2},
              '#9':{'diam':1.128*inch,'area':1*inch**2},
              '#10':{'diam':1.27*inch,'area':1.27*inch**2},
              '#11':{'diam':1.41*inch,'area':1.56*inch**2}}